### PR TITLE
Quick regular expression fix + Per World support

### PR DESCRIPTION
**Pull request by Wundero**
Just made substrings optional, was an error on my part.

### CODE REVIEW

**Comment by Wundero** [comment]
Should address #28 as well.

**Comment by Puharesource** [comment]
I think the per world support mainly addresses something like, when a player enters a new world it'll display a title message and that the tabmenu's header / footer is different in different worlds, however, this is a nice change as well. :)

Also, (?i) means ignore case in regex.
Also, substrings were optional as I've been testing it on my clients' server that already had a header / footer setup, prior to the substring addition.

**Comment by Puharesource** [comment]
Oops I forgot how to merge xD

**Comment by mibby** [comment]
@Wundero This breaks compiling. Reverting these 3 commits, I'm able to compile the source with gradle again.

https://github.com/Wundero/TitleManager/commit/fe55619c893085f766265acaa5b8e2eb99fc2677
https://github.com/Wundero/TitleManager/commit/ba7531ef41f663a3f5b19048e9f21f99dafe4685
https://github.com/Wundero/TitleManager/commit/b1a856b18aa861997edea296ee946a2d95ed192b

**Comment by mibby** [comment]
This PR is just chock full of breaking things.

```
[03:01:56] [Server thread/WARN]: [TitleManager] Task #333 for TitleManager v1.5.10 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 1
	at io.puharesource.mc.titlemanager.api.variables.VariableManager.replaceText(VariableManager.java:96) ~[?:?]
	at io.puharesource.mc.titlemanager.api.TextConverter.setVariables(TextConverter.java:28) ~[?:?]
	at io.puharesource.mc.titlemanager.api.TitleObject.send(TitleObject.java:78) ~[?:?]
	at io.puharesource.mc.titlemanager.listeners.ListenerConnection$2.run(ListenerConnection.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c8a0d06-58d972f]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c8a0d06-58d972f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-c8a0d06-58d972f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-c8a0d06-58d972f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-c8a0d06-58d972f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-c8a0d06-58d972f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by Puharesource** [comment]
@mibby, @Wundero doesn't seem to write his changes in an IDE, so I always end up fixing his PR's once I've pulled them (something that I hadn't had the time to fix until now, expect a new commit in a bit)

**Comment by Puharesource** [comment]
I've currently rewriting the way that TitleManager schedules its tasks, due to the fact that sometimes animations stop working. (Though this might just be due to forks of Spigot, such as PaperSpigot, though I still want to fix it)

Doing this, will also make scheduling of animations, etc... Completely asynchronous, which in turn, will make it to where even though the server is lagging, animations should still keep looking smooth, (unless that lag is network lag, of course)

**Comment by mibby** [comment]
Great. I'll be ready to test when it is available. :)

**Comment by Puharesource** [comment]
31a16fc96cee3b6d80c33db1fc81d31feaf5698c compiles and animations seems to be working ^^

**Comment by Wundero** [comment]
Oops, looks like I forgot to remove the + symbols from copy/pasting my changes to my own fork. I am still not so great with github :/. That's probably partially why it would not compile lel. Sorry about that.

**Comment by Puharesource** [comment]
Haha, no problem ;)

**Comment by mibby** [comment]
Manually compiled. Seems to be functioning just fine. :)

**Comment by Puharesource** [comment]
Perfect ^^

**Pull request merged**
