### PR TITLE
Added Minecraft 1.18 ScoreBoard support

### PR DESCRIPTION
**Pull request by Rothes**
This PR make TitleManager supports Minecraft 1.18 ScoreBoard, since methods are obfuscated.

### CODE REVIEW

**Comment by Puharesource** [comment]
Thank you! I'll have a look at this in a minute!

**Comment by SomeKoder** [comment]
Any ETA for release on spigot?
Thanks!

**Comment by Puharesource** [comment]
I'll try to release it tomorrow

**Comment by Rothes** [comment]
Note that actually I only tested ScoreBoard function..

**Pull request merged**
